workflow:
  name: default
  auto_cancel:
    on_job_failure: none
    on_new_commit: none
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
      when: always
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
      auto_cancel:
        on_new_commit: interruptible
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - when: never

stages:
  - jobs
  - unit-tests
  - publish

default:
  image:
    name: pfeiffermax/python-poetry:1.17.0-poetry2.2.1-python3.12.12-trixie
  tags:
    - static-k8s

variables:
  PY_COLORS:
    value: '1'
  FORCE_COLOR:
    value: '1'

checkstyle/build-pipeline:
  before_script:
    - |
      #!/usr/bin/env sh
      set -o errexit -o nounset -o xtrace
      section="$(date +'%s'):before_script_setup"
      printf '\e[0Ksection_start:%s[collapsed=true]\r\e[0K%s\n' "${section}" "setup"
      # shellcheck disable=SC2086
      poetry install
      . ".venv/bin/activate"
      printf '\e[0Ksection_end:%s\r\e[0K\n' "${section}"
  after_script:
    - |
      #!/usr/bin/env sh
      set -o errexit -o nounset -o xtrace
      section="$(date +'%s'):after_script_setup"
      printf '\e[0Ksection_start:%s[collapsed=true]\r\e[0K%s\n' "${section}" "setup"
      # shellcheck disable=SC2086
      poetry install
      . ".venv/bin/activate"
      printf '\e[0Ksection_end:%s\r\e[0K\n' "${section}"
    - echo Do nothing.
  script:
    - exec sh -c "gcip2 build-pipeline -f pipelines/checkstyle/ci.py"
  stage: jobs
  tags:
    - static-k8s
  artifacts:
    paths:
      - out
  interruptible: true

checkstyle/trigger-pipeline:
  variables:
    PARENT_PIPELINE_ID: ${CI_PIPELINE_ID}
  stage: jobs
  needs:
    - checkstyle/build-pipeline
  interruptible: false
  trigger:
    strategy: depend
    include:
      - job: checkstyle/build-pipeline
        artifact: out/pipeline.gitlab-ci.yml
    forward:
      yaml_variables: true
      pipeline_variables: true

multipipeline/build-pipeline:
  before_script:
    - |
      #!/usr/bin/env sh
      set -o errexit -o nounset -o xtrace
      section="$(date +'%s'):before_script_setup"
      printf '\e[0Ksection_start:%s[collapsed=true]\r\e[0K%s\n' "${section}" "setup"
      # shellcheck disable=SC2086
      poetry install
      . ".venv/bin/activate"
      printf '\e[0Ksection_end:%s\r\e[0K\n' "${section}"
  after_script:
    - |
      #!/usr/bin/env sh
      set -o errexit -o nounset -o xtrace
      section="$(date +'%s'):after_script_setup"
      printf '\e[0Ksection_start:%s[collapsed=true]\r\e[0K%s\n' "${section}" "setup"
      # shellcheck disable=SC2086
      poetry install
      . ".venv/bin/activate"
      printf '\e[0Ksection_end:%s\r\e[0K\n' "${section}"
    - echo Do nothing.
  script:
    - exec sh -c "gcip2 build-pipeline -f pipelines/multipipeline/ci.py"
  stage: jobs
  tags:
    - static-k8s
  artifacts:
    paths:
      - out
  interruptible: true

multipipeline/trigger-pipeline:
  variables:
    PARENT_PIPELINE_ID: ${CI_PIPELINE_ID}
  stage: jobs
  needs:
    - multipipeline/build-pipeline
  interruptible: false
  trigger:
    strategy: depend
    include:
      - job: multipipeline/build-pipeline
        artifact: out/pipeline.gitlab-ci.yml
    forward:
      yaml_variables: true
      pipeline_variables: true

integration/build-pipeline:
  before_script:
    - |
      #!/usr/bin/env sh
      set -o errexit -o nounset -o xtrace
      section="$(date +'%s'):before_script_setup"
      printf '\e[0Ksection_start:%s[collapsed=true]\r\e[0K%s\n' "${section}" "setup"
      # shellcheck disable=SC2086
      poetry install
      . ".venv/bin/activate"
      printf '\e[0Ksection_end:%s\r\e[0K\n' "${section}"
  after_script:
    - |
      #!/usr/bin/env sh
      set -o errexit -o nounset -o xtrace
      section="$(date +'%s'):after_script_setup"
      printf '\e[0Ksection_start:%s[collapsed=true]\r\e[0K%s\n' "${section}" "setup"
      # shellcheck disable=SC2086
      poetry install
      . ".venv/bin/activate"
      printf '\e[0Ksection_end:%s\r\e[0K\n' "${section}"
    - echo Do nothing.
  script:
    - exec sh -c "gcip2 build-pipeline -f pipelines/integration/ci.py"
  stage: jobs
  tags:
    - static-k8s
  artifacts:
    paths:
      - out
  interruptible: true

integration/trigger-pipeline:
  variables:
    PARENT_PIPELINE_ID: ${CI_PIPELINE_ID}
  stage: jobs
  needs:
    - integration/build-pipeline
  interruptible: false
  trigger:
    strategy: depend
    include:
      - job: integration/build-pipeline
        artifact: out/pipeline.gitlab-ci.yml
    forward:
      yaml_variables: true
      pipeline_variables: true

publish/build-pipeline:
  before_script:
    - |
      #!/usr/bin/env sh
      set -o errexit -o nounset -o xtrace
      section="$(date +'%s'):before_script_setup"
      printf '\e[0Ksection_start:%s[collapsed=true]\r\e[0K%s\n' "${section}" "setup"
      # shellcheck disable=SC2086
      poetry install
      . ".venv/bin/activate"
      printf '\e[0Ksection_end:%s\r\e[0K\n' "${section}"
  after_script:
    - |
      #!/usr/bin/env sh
      set -o errexit -o nounset -o xtrace
      section="$(date +'%s'):after_script_setup"
      printf '\e[0Ksection_start:%s[collapsed=true]\r\e[0K%s\n' "${section}" "setup"
      # shellcheck disable=SC2086
      poetry install
      . ".venv/bin/activate"
      printf '\e[0Ksection_end:%s\r\e[0K\n' "${section}"
    - echo Do nothing.
  script:
    - exec sh -c "gcip2 build-pipeline -f pipelines/publish/ci.py"
  stage: publish
  tags:
    - static-k8s
  artifacts:
    paths:
      - out
  interruptible: true

publish/trigger-pipeline:
  variables:
    PARENT_PIPELINE_ID: ${CI_PIPELINE_ID}
  stage: publish
  needs:
    - publish/build-pipeline
  interruptible: false
  trigger:
    strategy: depend
    include:
      - job: publish/build-pipeline
        artifact: out/pipeline.gitlab-ci.yml
    forward:
      yaml_variables: true
      pipeline_variables: true

unit-tests:job:
  before_script:
    - |
      #!/usr/bin/env sh
      set -o errexit -o nounset -o xtrace
      section="$(date +'%s'):before_script_setup"
      printf '\e[0Ksection_start:%s[collapsed=true]\r\e[0K%s\n' "${section}" "setup"
      # shellcheck disable=SC2086
      poetry install
      . ".venv/bin/activate"
      printf '\e[0Ksection_end:%s\r\e[0K\n' "${section}"
  after_script:
    - |
      #!/usr/bin/env sh
      set -o errexit -o nounset -o xtrace
      section="$(date +'%s'):after_script_setup"
      printf '\e[0Ksection_start:%s[collapsed=true]\r\e[0K%s\n' "${section}" "setup"
      # shellcheck disable=SC2086
      poetry install
      . ".venv/bin/activate"
      printf '\e[0Ksection_end:%s\r\e[0K\n' "${section}"
    - echo Do nothing.
  script:
    - pytest -v tests/unit/test_job.py --junitxml=pytest.xml --cov=gcip2 --cov-report=term
      --cov-report=xml:coverage.xml
  stage: unit-tests
  artifacts:
    paths:
      - coverage.xml
      - pytest.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit:
        - pytest.xml
  coverage: /TOTAL.*?(\d+%)$/
  interruptible: true

unit-tests:pipeline:
  before_script:
    - |
      #!/usr/bin/env sh
      set -o errexit -o nounset -o xtrace
      section="$(date +'%s'):before_script_setup"
      printf '\e[0Ksection_start:%s[collapsed=true]\r\e[0K%s\n' "${section}" "setup"
      # shellcheck disable=SC2086
      poetry install
      . ".venv/bin/activate"
      printf '\e[0Ksection_end:%s\r\e[0K\n' "${section}"
  after_script:
    - |
      #!/usr/bin/env sh
      set -o errexit -o nounset -o xtrace
      section="$(date +'%s'):after_script_setup"
      printf '\e[0Ksection_start:%s[collapsed=true]\r\e[0K%s\n' "${section}" "setup"
      # shellcheck disable=SC2086
      poetry install
      . ".venv/bin/activate"
      printf '\e[0Ksection_end:%s\r\e[0K\n' "${section}"
    - echo Do nothing.
  script:
    - pytest -v tests/unit/test_pipeline.py --junitxml=pytest.xml --cov=gcip2 --cov-report=term
      --cov-report=xml:coverage.xml
  stage: unit-tests
  artifacts:
    paths:
      - coverage.xml
      - pytest.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit:
        - pytest.xml
  coverage: /TOTAL.*?(\d+%)$/
  interruptible: true
