workflow:
  name: default
  auto_cancel:
    on_job_failure: none
    on_new_commit: none
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
      when: always
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
      auto_cancel:
        on_new_commit: interruptible
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - when: never

stages:
  - jobs
  - unit-tests
  - publish

default:
  image:
    name: af.pivlab.space/astral-sh/uv:python3.12
  tags:
    - static-k8s

variables:
  PY_COLORS:
    value: '1'
  FORCE_COLOR:
    value: '1'
  FF_TIMESTAMPS:
    value: 'true'

checkstyle/build-pipeline:
  before_script:
    - |
      #!/usr/bin/env sh
      set -o errexit -o nounset -o xtrace
      section="$(date +'%s'):before_script_setup"
      printf '\e[0Ksection_start:%s[collapsed=true]\r\e[0K%s\n' "${section}" "setup"
      CI_RUNNER_DIR="$(readlink -f "${CI_RUNNER_DIR:-.}")"
      export CI_RUNNER_DIR
      export UV_LINK_MODE=copy
      uv sync --directory "${CI_RUNNER_DIR}"
      venv="$(dirname "$(dirname "$(uv run --directory "${CI_RUNNER_DIR}" which python)")")"
      echo "using venv '${venv}'"
      . "${venv}/bin/activate"
      printf '\e[0Ksection_end:%s\r\e[0K\n' "${section}"
  after_script:
    - |
      #!/usr/bin/env sh
      set -o errexit -o nounset -o xtrace
      section="$(date +'%s'):after_script_setup"
      printf '\e[0Ksection_start:%s[collapsed=true]\r\e[0K%s\n' "${section}" "setup"
      CI_RUNNER_DIR="$(readlink -f "${CI_RUNNER_DIR:-.}")"
      export CI_RUNNER_DIR
      export UV_LINK_MODE=copy
      uv sync --directory "${CI_RUNNER_DIR}"
      venv="$(dirname "$(dirname "$(uv run --directory "${CI_RUNNER_DIR}" which python)")")"
      echo "using venv '${venv}'"
      . "${venv}/bin/activate"
      printf '\e[0Ksection_end:%s\r\e[0K\n' "${section}"
    - echo Do nothing.
  script:
    - exec sh -c "gcip2 build-pipeline -f pipelines/checkstyle/ci.py"
  stage: jobs
  tags:
    - static-k8s
  artifacts:
    paths:
      - out
  interruptible: true

checkstyle/trigger-pipeline:
  variables:
    PARENT_PIPELINE_ID: ${CI_PIPELINE_ID}
    PARENT_PIPELINE_SOURCE: ${CI_PIPELINE_SOURCE}
  stage: jobs
  needs:
    - checkstyle/build-pipeline
  interruptible: false
  trigger:
    strategy: depend
    include:
      - job: checkstyle/build-pipeline
        artifact: out/pipeline.gitlab-ci.yml
    forward:
      yaml_variables: true
      pipeline_variables: true

initialization/build-pipeline:
  before_script:
    - |
      #!/usr/bin/env sh
      set -o errexit -o nounset -o xtrace
      section="$(date +'%s'):before_script_setup"
      printf '\e[0Ksection_start:%s[collapsed=true]\r\e[0K%s\n' "${section}" "setup"
      CI_RUNNER_DIR="$(readlink -f "${CI_RUNNER_DIR:-.}")"
      export CI_RUNNER_DIR
      export UV_LINK_MODE=copy
      uv sync --directory "${CI_RUNNER_DIR}"
      venv="$(dirname "$(dirname "$(uv run --directory "${CI_RUNNER_DIR}" which python)")")"
      echo "using venv '${venv}'"
      . "${venv}/bin/activate"
      printf '\e[0Ksection_end:%s\r\e[0K\n' "${section}"
  after_script:
    - |
      #!/usr/bin/env sh
      set -o errexit -o nounset -o xtrace
      section="$(date +'%s'):after_script_setup"
      printf '\e[0Ksection_start:%s[collapsed=true]\r\e[0K%s\n' "${section}" "setup"
      CI_RUNNER_DIR="$(readlink -f "${CI_RUNNER_DIR:-.}")"
      export CI_RUNNER_DIR
      export UV_LINK_MODE=copy
      uv sync --directory "${CI_RUNNER_DIR}"
      venv="$(dirname "$(dirname "$(uv run --directory "${CI_RUNNER_DIR}" which python)")")"
      echo "using venv '${venv}'"
      . "${venv}/bin/activate"
      printf '\e[0Ksection_end:%s\r\e[0K\n' "${section}"
    - echo Do nothing.
  script:
    - exec sh -c "gcip2 build-pipeline -f pipelines/initialization/ci.py"
  stage: jobs
  tags:
    - static-k8s
  artifacts:
    paths:
      - out
  interruptible: true

initialization/trigger-pipeline:
  variables:
    PARENT_PIPELINE_ID: ${CI_PIPELINE_ID}
    PARENT_PIPELINE_SOURCE: ${CI_PIPELINE_SOURCE}
  stage: jobs
  needs:
    - initialization/build-pipeline
  interruptible: false
  trigger:
    strategy: depend
    include:
      - job: initialization/build-pipeline
        artifact: out/pipeline.gitlab-ci.yml
    forward:
      yaml_variables: true
      pipeline_variables: true

tasks/build-pipeline:
  before_script:
    - |
      #!/usr/bin/env sh
      set -o errexit -o nounset -o xtrace
      section="$(date +'%s'):before_script_setup"
      printf '\e[0Ksection_start:%s[collapsed=true]\r\e[0K%s\n' "${section}" "setup"
      CI_RUNNER_DIR="$(readlink -f "${CI_RUNNER_DIR:-.}")"
      export CI_RUNNER_DIR
      export UV_LINK_MODE=copy
      uv sync --directory "${CI_RUNNER_DIR}"
      venv="$(dirname "$(dirname "$(uv run --directory "${CI_RUNNER_DIR}" which python)")")"
      echo "using venv '${venv}'"
      . "${venv}/bin/activate"
      printf '\e[0Ksection_end:%s\r\e[0K\n' "${section}"
  after_script:
    - |
      #!/usr/bin/env sh
      set -o errexit -o nounset -o xtrace
      section="$(date +'%s'):after_script_setup"
      printf '\e[0Ksection_start:%s[collapsed=true]\r\e[0K%s\n' "${section}" "setup"
      CI_RUNNER_DIR="$(readlink -f "${CI_RUNNER_DIR:-.}")"
      export CI_RUNNER_DIR
      export UV_LINK_MODE=copy
      uv sync --directory "${CI_RUNNER_DIR}"
      venv="$(dirname "$(dirname "$(uv run --directory "${CI_RUNNER_DIR}" which python)")")"
      echo "using venv '${venv}'"
      . "${venv}/bin/activate"
      printf '\e[0Ksection_end:%s\r\e[0K\n' "${section}"
    - echo Do nothing.
  script:
    - exec sh -c "gcip2 build-pipeline -f pipelines/tasks/ci.py"
  stage: jobs
  tags:
    - static-k8s
  artifacts:
    paths:
      - out
  interruptible: true

tasks/trigger-pipeline:
  variables:
    PARENT_PIPELINE_ID: ${CI_PIPELINE_ID}
    PARENT_PIPELINE_SOURCE: ${CI_PIPELINE_SOURCE}
  stage: jobs
  needs:
    - tasks/build-pipeline
  interruptible: false
  trigger:
    strategy: depend
    include:
      - job: tasks/build-pipeline
        artifact: out/pipeline.gitlab-ci.yml
    forward:
      yaml_variables: true
      pipeline_variables: true

vault/build-pipeline:
  before_script:
    - |
      #!/usr/bin/env sh
      set -o errexit -o nounset -o xtrace
      section="$(date +'%s'):before_script_setup"
      printf '\e[0Ksection_start:%s[collapsed=true]\r\e[0K%s\n' "${section}" "setup"
      CI_RUNNER_DIR="$(readlink -f "${CI_RUNNER_DIR:-.}")"
      export CI_RUNNER_DIR
      export UV_LINK_MODE=copy
      uv sync --directory "${CI_RUNNER_DIR}"
      venv="$(dirname "$(dirname "$(uv run --directory "${CI_RUNNER_DIR}" which python)")")"
      echo "using venv '${venv}'"
      . "${venv}/bin/activate"
      printf '\e[0Ksection_end:%s\r\e[0K\n' "${section}"
  after_script:
    - |
      #!/usr/bin/env sh
      set -o errexit -o nounset -o xtrace
      section="$(date +'%s'):after_script_setup"
      printf '\e[0Ksection_start:%s[collapsed=true]\r\e[0K%s\n' "${section}" "setup"
      CI_RUNNER_DIR="$(readlink -f "${CI_RUNNER_DIR:-.}")"
      export CI_RUNNER_DIR
      export UV_LINK_MODE=copy
      uv sync --directory "${CI_RUNNER_DIR}"
      venv="$(dirname "$(dirname "$(uv run --directory "${CI_RUNNER_DIR}" which python)")")"
      echo "using venv '${venv}'"
      . "${venv}/bin/activate"
      printf '\e[0Ksection_end:%s\r\e[0K\n' "${section}"
    - echo Do nothing.
  script:
    - exec sh -c "gcip2 build-pipeline -f pipelines/vault/ci.py"
  stage: jobs
  tags:
    - static-k8s
  artifacts:
    paths:
      - out
  interruptible: true

vault/trigger-pipeline:
  variables:
    PARENT_PIPELINE_ID: ${CI_PIPELINE_ID}
    PARENT_PIPELINE_SOURCE: ${CI_PIPELINE_SOURCE}
  stage: jobs
  needs:
    - vault/build-pipeline
  interruptible: false
  trigger:
    strategy: depend
    include:
      - job: vault/build-pipeline
        artifact: out/pipeline.gitlab-ci.yml
    forward:
      yaml_variables: true
      pipeline_variables: true

multipipeline/build-pipeline:
  before_script:
    - |
      #!/usr/bin/env sh
      set -o errexit -o nounset -o xtrace
      section="$(date +'%s'):before_script_setup"
      printf '\e[0Ksection_start:%s[collapsed=true]\r\e[0K%s\n' "${section}" "setup"
      CI_RUNNER_DIR="$(readlink -f "${CI_RUNNER_DIR:-.}")"
      export CI_RUNNER_DIR
      export UV_LINK_MODE=copy
      uv sync --directory "${CI_RUNNER_DIR}"
      venv="$(dirname "$(dirname "$(uv run --directory "${CI_RUNNER_DIR}" which python)")")"
      echo "using venv '${venv}'"
      . "${venv}/bin/activate"
      printf '\e[0Ksection_end:%s\r\e[0K\n' "${section}"
  after_script:
    - |
      #!/usr/bin/env sh
      set -o errexit -o nounset -o xtrace
      section="$(date +'%s'):after_script_setup"
      printf '\e[0Ksection_start:%s[collapsed=true]\r\e[0K%s\n' "${section}" "setup"
      CI_RUNNER_DIR="$(readlink -f "${CI_RUNNER_DIR:-.}")"
      export CI_RUNNER_DIR
      export UV_LINK_MODE=copy
      uv sync --directory "${CI_RUNNER_DIR}"
      venv="$(dirname "$(dirname "$(uv run --directory "${CI_RUNNER_DIR}" which python)")")"
      echo "using venv '${venv}'"
      . "${venv}/bin/activate"
      printf '\e[0Ksection_end:%s\r\e[0K\n' "${section}"
    - echo Do nothing.
  script:
    - exec sh -c "gcip2 build-pipeline -f pipelines/multipipeline/ci.py"
  stage: jobs
  tags:
    - static-k8s
  artifacts:
    paths:
      - out
  interruptible: true

multipipeline/trigger-pipeline:
  variables:
    PARENT_PIPELINE_ID: ${CI_PIPELINE_ID}
    PARENT_PIPELINE_SOURCE: ${CI_PIPELINE_SOURCE}
  stage: jobs
  needs:
    - multipipeline/build-pipeline
  interruptible: false
  trigger:
    strategy: depend
    include:
      - job: multipipeline/build-pipeline
        artifact: out/pipeline.gitlab-ci.yml
    forward:
      yaml_variables: true
      pipeline_variables: true

integration/build-pipeline:
  before_script:
    - |
      #!/usr/bin/env sh
      set -o errexit -o nounset -o xtrace
      section="$(date +'%s'):before_script_setup"
      printf '\e[0Ksection_start:%s[collapsed=true]\r\e[0K%s\n' "${section}" "setup"
      CI_RUNNER_DIR="$(readlink -f "${CI_RUNNER_DIR:-.}")"
      export CI_RUNNER_DIR
      export UV_LINK_MODE=copy
      uv sync --directory "${CI_RUNNER_DIR}"
      venv="$(dirname "$(dirname "$(uv run --directory "${CI_RUNNER_DIR}" which python)")")"
      echo "using venv '${venv}'"
      . "${venv}/bin/activate"
      printf '\e[0Ksection_end:%s\r\e[0K\n' "${section}"
  after_script:
    - |
      #!/usr/bin/env sh
      set -o errexit -o nounset -o xtrace
      section="$(date +'%s'):after_script_setup"
      printf '\e[0Ksection_start:%s[collapsed=true]\r\e[0K%s\n' "${section}" "setup"
      CI_RUNNER_DIR="$(readlink -f "${CI_RUNNER_DIR:-.}")"
      export CI_RUNNER_DIR
      export UV_LINK_MODE=copy
      uv sync --directory "${CI_RUNNER_DIR}"
      venv="$(dirname "$(dirname "$(uv run --directory "${CI_RUNNER_DIR}" which python)")")"
      echo "using venv '${venv}'"
      . "${venv}/bin/activate"
      printf '\e[0Ksection_end:%s\r\e[0K\n' "${section}"
    - echo Do nothing.
  script:
    - exec sh -c "gcip2 build-pipeline -f pipelines/integration/ci.py"
  stage: jobs
  tags:
    - static-k8s
  artifacts:
    paths:
      - out
  interruptible: true

integration/trigger-pipeline:
  variables:
    PARENT_PIPELINE_ID: ${CI_PIPELINE_ID}
    PARENT_PIPELINE_SOURCE: ${CI_PIPELINE_SOURCE}
  stage: jobs
  needs:
    - integration/build-pipeline
  interruptible: false
  trigger:
    strategy: depend
    include:
      - job: integration/build-pipeline
        artifact: out/pipeline.gitlab-ci.yml
    forward:
      yaml_variables: true
      pipeline_variables: true

unit-tests:job:
  before_script:
    - |
      #!/usr/bin/env sh
      set -o errexit -o nounset -o xtrace
      section="$(date +'%s'):before_script_setup"
      printf '\e[0Ksection_start:%s[collapsed=true]\r\e[0K%s\n' "${section}" "setup"
      CI_RUNNER_DIR="$(readlink -f "${CI_RUNNER_DIR:-.}")"
      export CI_RUNNER_DIR
      export UV_LINK_MODE=copy
      uv sync --directory "${CI_RUNNER_DIR}"
      venv="$(dirname "$(dirname "$(uv run --directory "${CI_RUNNER_DIR}" which python)")")"
      echo "using venv '${venv}'"
      . "${venv}/bin/activate"
      printf '\e[0Ksection_end:%s\r\e[0K\n' "${section}"
  after_script:
    - |
      #!/usr/bin/env sh
      set -o errexit -o nounset -o xtrace
      section="$(date +'%s'):after_script_setup"
      printf '\e[0Ksection_start:%s[collapsed=true]\r\e[0K%s\n' "${section}" "setup"
      CI_RUNNER_DIR="$(readlink -f "${CI_RUNNER_DIR:-.}")"
      export CI_RUNNER_DIR
      export UV_LINK_MODE=copy
      uv sync --directory "${CI_RUNNER_DIR}"
      venv="$(dirname "$(dirname "$(uv run --directory "${CI_RUNNER_DIR}" which python)")")"
      echo "using venv '${venv}'"
      . "${venv}/bin/activate"
      printf '\e[0Ksection_end:%s\r\e[0K\n' "${section}"
    - echo Do nothing.
  script:
    - pytest -v tests/unit/test_job.py --junitxml=pytest.xml --cov=gcip2.pipeline_core
      --cov-report=term --cov-report=xml:coverage.xml
  stage: unit-tests
  artifacts:
    paths:
      - coverage.xml
      - pytest.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit:
        - pytest.xml
  coverage: /TOTAL.*?(\d+%)$/
  interruptible: true

unit-tests:pipeline:
  before_script:
    - |
      #!/usr/bin/env sh
      set -o errexit -o nounset -o xtrace
      section="$(date +'%s'):before_script_setup"
      printf '\e[0Ksection_start:%s[collapsed=true]\r\e[0K%s\n' "${section}" "setup"
      CI_RUNNER_DIR="$(readlink -f "${CI_RUNNER_DIR:-.}")"
      export CI_RUNNER_DIR
      export UV_LINK_MODE=copy
      uv sync --directory "${CI_RUNNER_DIR}"
      venv="$(dirname "$(dirname "$(uv run --directory "${CI_RUNNER_DIR}" which python)")")"
      echo "using venv '${venv}'"
      . "${venv}/bin/activate"
      printf '\e[0Ksection_end:%s\r\e[0K\n' "${section}"
  after_script:
    - |
      #!/usr/bin/env sh
      set -o errexit -o nounset -o xtrace
      section="$(date +'%s'):after_script_setup"
      printf '\e[0Ksection_start:%s[collapsed=true]\r\e[0K%s\n' "${section}" "setup"
      CI_RUNNER_DIR="$(readlink -f "${CI_RUNNER_DIR:-.}")"
      export CI_RUNNER_DIR
      export UV_LINK_MODE=copy
      uv sync --directory "${CI_RUNNER_DIR}"
      venv="$(dirname "$(dirname "$(uv run --directory "${CI_RUNNER_DIR}" which python)")")"
      echo "using venv '${venv}'"
      . "${venv}/bin/activate"
      printf '\e[0Ksection_end:%s\r\e[0K\n' "${section}"
    - echo Do nothing.
  script:
    - pytest -v tests/unit/test_pipeline.py --junitxml=pytest.xml --cov=gcip2.pipeline_core
      --cov-report=term --cov-report=xml:coverage.xml
  stage: unit-tests
  artifacts:
    paths:
      - coverage.xml
      - pytest.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit:
        - pytest.xml
  coverage: /TOTAL.*?(\d+%)$/
  interruptible: true

unit-tests:tasks:
  before_script:
    - |
      #!/usr/bin/env sh
      set -o errexit -o nounset -o xtrace
      section="$(date +'%s'):before_script_setup"
      printf '\e[0Ksection_start:%s[collapsed=true]\r\e[0K%s\n' "${section}" "setup"
      CI_RUNNER_DIR="$(readlink -f "${CI_RUNNER_DIR:-.}")"
      export CI_RUNNER_DIR
      export UV_LINK_MODE=copy
      uv sync --directory "${CI_RUNNER_DIR}"
      venv="$(dirname "$(dirname "$(uv run --directory "${CI_RUNNER_DIR}" which python)")")"
      echo "using venv '${venv}'"
      . "${venv}/bin/activate"
      printf '\e[0Ksection_end:%s\r\e[0K\n' "${section}"
  after_script:
    - |
      #!/usr/bin/env sh
      set -o errexit -o nounset -o xtrace
      section="$(date +'%s'):after_script_setup"
      printf '\e[0Ksection_start:%s[collapsed=true]\r\e[0K%s\n' "${section}" "setup"
      CI_RUNNER_DIR="$(readlink -f "${CI_RUNNER_DIR:-.}")"
      export CI_RUNNER_DIR
      export UV_LINK_MODE=copy
      uv sync --directory "${CI_RUNNER_DIR}"
      venv="$(dirname "$(dirname "$(uv run --directory "${CI_RUNNER_DIR}" which python)")")"
      echo "using venv '${venv}'"
      . "${venv}/bin/activate"
      printf '\e[0Ksection_end:%s\r\e[0K\n' "${section}"
    - echo Do nothing.
  script:
    - pytest -v tests/unit/test_tasks.py --junitxml=pytest.xml --cov=gcip2.tasks_core
      --cov-report=term --cov-report=xml:coverage.xml
  stage: unit-tests
  artifacts:
    paths:
      - coverage.xml
      - pytest.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit:
        - pytest.xml
  coverage: /TOTAL.*?(\d+%)$/
  interruptible: true

check-package-version:
  image:
    name: af.pivlab.space/astral-sh/uv:python3.12
  before_script:
    - |
      #!/usr/bin/env sh
      set -o errexit -o nounset -o xtrace
      section="$(date +'%s'):before_script_setup"
      printf '\e[0Ksection_start:%s[collapsed=true]\r\e[0K%s\n' "${section}" "setup"
      CI_RUNNER_DIR="$(readlink -f "${CI_RUNNER_DIR:-.}")"
      export CI_RUNNER_DIR
      export UV_LINK_MODE=copy
      uv sync --directory "${CI_RUNNER_DIR}"
      venv="$(dirname "$(dirname "$(uv run --directory "${CI_RUNNER_DIR}" which python)")")"
      echo "using venv '${venv}'"
      . "${venv}/bin/activate"
      printf '\e[0Ksection_end:%s\r\e[0K\n' "${section}"
  after_script:
    - |
      #!/usr/bin/env sh
      set -o errexit -o nounset -o xtrace
      section="$(date +'%s'):after_script_setup"
      printf '\e[0Ksection_start:%s[collapsed=true]\r\e[0K%s\n' "${section}" "setup"
      CI_RUNNER_DIR="$(readlink -f "${CI_RUNNER_DIR:-.}")"
      export CI_RUNNER_DIR
      export UV_LINK_MODE=copy
      uv sync --directory "${CI_RUNNER_DIR}"
      venv="$(dirname "$(dirname "$(uv run --directory "${CI_RUNNER_DIR}" which python)")")"
      echo "using venv '${venv}'"
      . "${venv}/bin/activate"
      printf '\e[0Ksection_end:%s\r\e[0K\n' "${section}"
    - echo Do nothing.
  script:
    - |
      #!/usr/bin/env sh
      set -o errexit -o nounset -o xtrace
      section="$(date +'%s'):setup"
      printf '\e[0Ksection_start:%s[collapsed=true]\r\e[0K%s\n' "${section}" "setup"
      CI_RUNNER_DIR="$(readlink -f "${CI_RUNNER_DIR:-.}")"
      export CI_RUNNER_DIR
      export UV_LINK_MODE=copy
      uv sync --directory "${CI_RUNNER_DIR}"
      venv="$(dirname "$(dirname "$(uv run --directory "${CI_RUNNER_DIR}" which python)")")"
      echo "using venv '${venv}'"
      . "${venv}/bin/activate"
      printf '\e[0Ksection_end:%s\r\e[0K\n' "${section}"
    - dothat run ${CI_JOB_NAME}
  stage: publish
  interruptible: true

create-version-tag:
  image:
    name: af.pivlab.space/astral-sh/uv:python3.12
  before_script:
    - |
      #!/usr/bin/env sh
      set -o errexit -o nounset -o xtrace
      section="$(date +'%s'):before_script_setup"
      printf '\e[0Ksection_start:%s[collapsed=true]\r\e[0K%s\n' "${section}" "setup"
      CI_RUNNER_DIR="$(readlink -f "${CI_RUNNER_DIR:-.}")"
      export CI_RUNNER_DIR
      export UV_LINK_MODE=copy
      uv sync --directory "${CI_RUNNER_DIR}"
      venv="$(dirname "$(dirname "$(uv run --directory "${CI_RUNNER_DIR}" which python)")")"
      echo "using venv '${venv}'"
      . "${venv}/bin/activate"
      printf '\e[0Ksection_end:%s\r\e[0K\n' "${section}"
  after_script:
    - |
      #!/usr/bin/env sh
      set -o errexit -o nounset -o xtrace
      section="$(date +'%s'):after_script_setup"
      printf '\e[0Ksection_start:%s[collapsed=true]\r\e[0K%s\n' "${section}" "setup"
      CI_RUNNER_DIR="$(readlink -f "${CI_RUNNER_DIR:-.}")"
      export CI_RUNNER_DIR
      export UV_LINK_MODE=copy
      uv sync --directory "${CI_RUNNER_DIR}"
      venv="$(dirname "$(dirname "$(uv run --directory "${CI_RUNNER_DIR}" which python)")")"
      echo "using venv '${venv}'"
      . "${venv}/bin/activate"
      printf '\e[0Ksection_end:%s\r\e[0K\n' "${section}"
    - echo Do nothing.
  script:
    - |
      #!/usr/bin/env sh
      set -o errexit -o nounset -o xtrace
      section="$(date +'%s'):setup"
      printf '\e[0Ksection_start:%s[collapsed=true]\r\e[0K%s\n' "${section}" "setup"
      CI_RUNNER_DIR="$(readlink -f "${CI_RUNNER_DIR:-.}")"
      export CI_RUNNER_DIR
      export UV_LINK_MODE=copy
      uv sync --directory "${CI_RUNNER_DIR}"
      venv="$(dirname "$(dirname "$(uv run --directory "${CI_RUNNER_DIR}" which python)")")"
      echo "using venv '${venv}'"
      . "${venv}/bin/activate"
      printf '\e[0Ksection_end:%s\r\e[0K\n' "${section}"
    - dothat run ${CI_JOB_NAME}
  stage: publish
  needs:
    - check-package-version
  interruptible: true

publish-package:
  image:
    name: af.pivlab.space/astral-sh/uv:python3.12
  before_script:
    - |
      #!/usr/bin/env sh
      set -o errexit -o nounset -o xtrace
      section="$(date +'%s'):before_script_setup"
      printf '\e[0Ksection_start:%s[collapsed=true]\r\e[0K%s\n' "${section}" "setup"
      CI_RUNNER_DIR="$(readlink -f "${CI_RUNNER_DIR:-.}")"
      export CI_RUNNER_DIR
      export UV_LINK_MODE=copy
      uv sync --directory "${CI_RUNNER_DIR}"
      venv="$(dirname "$(dirname "$(uv run --directory "${CI_RUNNER_DIR}" which python)")")"
      echo "using venv '${venv}'"
      . "${venv}/bin/activate"
      printf '\e[0Ksection_end:%s\r\e[0K\n' "${section}"
  after_script:
    - |
      #!/usr/bin/env sh
      set -o errexit -o nounset -o xtrace
      section="$(date +'%s'):after_script_setup"
      printf '\e[0Ksection_start:%s[collapsed=true]\r\e[0K%s\n' "${section}" "setup"
      CI_RUNNER_DIR="$(readlink -f "${CI_RUNNER_DIR:-.}")"
      export CI_RUNNER_DIR
      export UV_LINK_MODE=copy
      uv sync --directory "${CI_RUNNER_DIR}"
      venv="$(dirname "$(dirname "$(uv run --directory "${CI_RUNNER_DIR}" which python)")")"
      echo "using venv '${venv}'"
      . "${venv}/bin/activate"
      printf '\e[0Ksection_end:%s\r\e[0K\n' "${section}"
    - echo Do nothing.
  script:
    - |
      #!/usr/bin/env sh
      set -o errexit -o nounset -o xtrace
      section="$(date +'%s'):setup"
      printf '\e[0Ksection_start:%s[collapsed=true]\r\e[0K%s\n' "${section}" "setup"
      CI_RUNNER_DIR="$(readlink -f "${CI_RUNNER_DIR:-.}")"
      export CI_RUNNER_DIR
      export UV_LINK_MODE=copy
      uv sync --directory "${CI_RUNNER_DIR}"
      venv="$(dirname "$(dirname "$(uv run --directory "${CI_RUNNER_DIR}" which python)")")"
      echo "using venv '${venv}'"
      . "${venv}/bin/activate"
      printf '\e[0Ksection_end:%s\r\e[0K\n' "${section}"
    - dothat run ${CI_JOB_NAME}
  stage: publish
  needs:
    - create-version-tag
  interruptible: true
