workflow:
  name: default
  auto_cancel:
    on_job_failure: none
    on_new_commit: none
  rules:
    - if: $CI_COMMIT_TAG =~ '/^v\d+\.\d+\.\d+$/'
      when: always
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always
    - when: never

default:
  image:
    name: pfeiffermax/python-poetry:1.17.0-poetry2.2.1-python3.12.12-trixie
  tags:
    - immortal

build-pipeline:
  before_script:
    - |
      #!/usr/bin/env sh
      set -o errexit -o nounset -o xtrace
      section="$(date +'%s'):setup"
      printf '\e[0Ksection_start:%s[collapsed=true]\r\e[0K%s\n' "${section}" "setup"
      # shellcheck disable=SC2086
      poetry install
      . ".venv/bin/activate"
      printf '\e[0Ksection_end:%s\r\e[0K\n' "${section}"
  script:
    - exec sh -c "gcip2 build-pipeline"
  artifacts:
    paths:
      - out

trigger-pipeline:
  variables:
    PARENT_PIPELINE_ID: ${CI_PIPELINE_ID}
  needs:
    - job: build-pipeline
      artifacts: true
  interruptible: false
  trigger:
    strategy: depend
    include:
      - job: build-pipeline
        artifact: out/pipeline.gitlab-ci.yml
    forward:
      yaml_variables: true
      pipeline_variables: true
