repos:
  - repo: local
    hooks:
      - id: build-gitlab-ci
        name: generate .gitlab-ci.yml
        entry: uv run -- dothat -- run -- build-gitlab-ci
        language: system
        pass_filenames: false
        always_run: true
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.1
    hooks:
      - id: ruff-format
        name: ruff format

      - id: ruff
        name: ruff check
        args:
          - --fix
