[extra]
version = "0.1.5"
test_repo = "rnd/gcip2-tests/initialization-test"

pipelines = [
    "initialization",
    "integration",
    "tasks",
    "vault",
    "multipipeline",
]

[extra.tests]
coverage-module = { "job" = "gcip2.pipeline_core", "pipeline" = "gcip2.pipeline_core", "tasks" = "gcip2.tasks_core" }
unit-tests = ["job", "pipeline", "tasks"]

[extra.tasks]
module = "_tasks"

[extra.targets.test-1]
param1 = "1"

[extra.targets.test-2]
param1 = "2"


[extra.secrets.vault.vault-with-approle]
url = "https://vault.pivlab.space"
auth_method = "approle"
app_role_id_env_var = "APP_ROLE_ID"
app_role_secret_id_env_var = "APP_ROLE_SECRET_ID"
mount_point = "rnd"
path = "infra/test"
env_vars = [{ value = "", field = "" }]

[extra.secrets.vault.vault-with-jwks]
url = "https://vault.pivlab.space"
auth_method = "jwks"
mount_point = "rnd"
path = "infra/test"

[extra.secrets.vault.pypi-token]
url = "https://vault.pivlab.space"
auth_method = "approle"
app_role_id_env_var = "APP_ROLE_ID"
app_role_secret_id_env_var = "APP_ROLE_SECRET_ID"
mount_point = "rnd"
path = "infra/pypi"

[extra.secrets.vault.gitlab-token]
url = "https://vault.pivlab.space"
auth_method = "approle"
app_role_id_env_var = "APP_ROLE_ID"
app_role_secret_id_env_var = "APP_ROLE_SECRET_ID"
mount_point = "rnd"
path = "infra/accounts/gitlab/ci"

[extra.secrets.vault.gl-pivlab-maintainer]
url = "https://vault.pivlab.space"
auth_method = "approle"
app_role_id_env_var = "APP_ROLE_ID"
app_role_secret_id_env_var = "APP_ROLE_SECRET_ID"
mount_point = "rnd"
path = "infra/accounts/gitlab/ci"
