repos:
  - repo: local
    hooks:
      - id: build-gitlab-ci
        name: generate .gitlab-ci.yml
        entry: uv run -- gcip2 -- build-gitlab-ci
        language: system
        pass_filenames: false
        always_run: true
      - id: ruff format
        name: ruff format
        entry: ruff format .
        description: Run ruff format
        language: system
        types: [python]
      - id: ruff check
        name: ruff check
        entry: ruff check --fix
        description: Run ruff check
        language: system
        types: [python]
