[project]
name = "dev"
version = "0.0.0"
description = ""
authors = [{ name = "Arsenii Nikulin", email = "studentq.work@yandex.ru" }]
license = { text = "PivLab Tech" }
readme = "README.md"
requires-python = ">=3.11,<4.0"

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
gcip2 = "^0.0.13"
pre-commit = "^4.6.1"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
