build-pipeline:
  script:
    - poetry install && . .venv/bin/activate
    - build-pipeline
  tags:
    - immortal

trigger-pipeline:
  trigger:
    include:
      - job: build-pipeline
        artifact: out/pipeline.gitlab-ci.yml
  needs:
    - job: build-pipeline
      artifacts: true
