from gcip2.builder_model import BasePipeline, TriggerPipeline, pipeline
from gcip2.ci_model import (
    Artifacts,
    ArtifactsReports,
    BaseInput,
    Default,
    GlobalVariables,
    Image,
    IncludeComponent,
    Job,
    JobVariables,
    Needs,
    Pipeline,
    Rule,
    RuleChanges,
    Stage,
    Trigger,
    Workflow,
    WorkflowAutoCancel,
    WorkflowAutoCancelOnJobFailure,
    WorkflowAutoCancelOnNewCommit,
)

__all__ = (
    "Trigger",
    "TriggerPipeline",
    "Pipeline",
    "Job",
    "Stage",
    "Image",
    "BasePipeline",
    "pipeline",
    "Needs",
    "Artifacts",
    "ArtifactsReports",
    "IncludeComponent",
    "BaseInput",
    "Workflow",
    "WorkflowAutoCancel",
    "Rule",
    "WorkflowAutoCancelOnJobFailure",
    "RuleChanges",
    "WorkflowAutoCancelOnNewCommit",
    "JobVariables",
    "GlobalVariables",
    "Default",
)
