from gcip2.builder_model import BasePipeline, TriggerPipeline, pipeline
from gcip2.ci_model import (
    Artifacts,
    ArtifactsReports,
    BaseInput,
    Image,
    IncludeComponent,
    Job,
    Needs,
    Pipeline,
    Stage,
    Trigger,
    Workflow,
    WorkflowAutoCancel,
    Rules,
    WorkflowAutoCancelOnJobFailure,
    WorkflowAutoCancelOnNewCommit,
    RulesChanges,
    JobVariables,
    GlobalVariables,
)

__all__ = (
    "Trigger",
    "TriggerPipeline",
    "Pipeline",
    "Job",
    "Stage",
    "Image",
    "BasePipeline",
    "pipeline",
    "Needs",
    "Artifacts",
    "ArtifactsReports",
    "IncludeComponent",
    "BaseInput",
    "Workflow",
    "WorkflowAutoCancel",
    "Rules",
    "WorkflowAutoCancelOnJobFailure",
    "RulesChanges",
    "WorkflowAutoCancelOnNewCommit",
)
